branch-defaults:
  main:
    environment: null
    group_suffix: null
global:
  application_name: swe1-app
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: swe1-app
  sc: git
  workspace_type: Application
